name: DisableVillagerBreeding
main: dvillager.breeding.DisableVillagerBreeding
version: 1.1
api-version: 26.2
author: Arkterion Labs
website: https://arkterion.com
description: Disables villager breeding